---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3

suites:
  - name: smoke-install-default
    run_list:
      - recipe[kubernetes-stack-test::install]
    verifier:
      inspec_tests:
        - test/smoke/default/default_test.rb
        - test/smoke/gcloud/gcloud_install_default_test.rb
        - test/smoke/kubectl/kubectl_install_default_test.rb
        - test/smoke/helm/helm_install_default_test.rb
    attributes:
      kubernetes-stack:
        kubectl:
          enabled: true,
          version: ""
        gcloud:
          enabled: true,
          version: ""
        helm:
          enabled: true,
          version: ""

  - name: smoke-install-specific-version
    run_list:
      - recipe[kubernetes-stack-test::install]
    verifier:
      inspec_tests:
        - test/smoke/default/default_test.rb
        - test/smoke/gcloud/gcloud_install_specific_version_test.rb
        - test/smoke/kubectl/kubectl_install_specific_version_test.rb
        - test/smoke/helm/helm_install_specific_version_test.rb
    attributes:
      kubernetes-stack:
        kubectl:
          enabled: true,
          version: "v1.7.0"
        gcloud:
          enabled: true,
          version: "158.0.0"
        helm:
          enabled: true,
          version: "v2.4.2"

  - name: smoke-uninstall
    run_list:
      - recipe[kubernetes-stack-test::uninstall]
    verifier:
      inspec_tests:
        - test/smoke/gcloud/gcloud_uninstall_test.rb
        - test/smoke/kubectl/kubectl_uninstall_test.rb
        - test/smoke/helm/helm_uninstall_test.rb
    attributes:
      kubernetes-stack:
        kubectl:
          enabled: true,
          version: ""
        gcloud:
          enabled: true,
          version: ""
        helm:
          enabled: true,
          version: ""
